global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'vuln_metrics'
    scrape_interval: 4s
    static_configs:
      - targets: ['host.docker.internal:8080']